### ISSUE TITLE
Crawler module

### ISSUE THREAD

**Issue by xanhacks** [poerschke/Uniscan#1]
$ perl uniscan.pl
Can't locate Uniscan/Crawler.pm in @INC (you may need to install the Uniscan::Crawler module) (@INC contains: ./Uniscan /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at uniscan.pl line 4.
BEGIN failed--compilation aborted at uniscan.pl line 4.

**Comment by xanhacks** [comment]
**Ok just need to replace this line:**
use lib "./Uniscan";
**by this two lines:**
use FindBin qw( $RealBin );
use lib $RealBin;
**in uniscan.pl**

**Comment by x11-repo** [comment]
Блять нихуя не понял. Как пофиксить та?

**Comment by x11-repo** [comment]
Ёбаные пендосы блять
